### ISSUE TITLE
rtm.start no longer working with bot OAuth token

### ISSUE THREAD

**Issue by nsbruce** [sand500/SlackLateX#12]
Where the Slack App bot OAuth token is set in secret.txt, the web request in bot.js

`https://slack.com/api/rtm.start?token=' + global.token + '&pretty=1`

now returns error 

`error | "not_allowed_token_type"`

**Comment by nsbruce** [comment]
https://api.slack.com/rtm

> New Slack apps may not use any Real Time Messaging API method. Create a classic app and use the V1 Oauth flow to use RTM.

**Comment by nsbruce** [comment]
OK So you can still make legacy apps that allow the rtm api and it all works! You need to use the bot token not the oauth token.

**Comment by sand500** [comment]
hmmm Is there a new API that replaces this?

**Comment by sand500** [comment]
ill update the readme
